// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * BlacklistApp is one entry in the user's custom blacklist.
 * ProcessName is what gets passed to `pkill -x` in kill mode.
 */
export class BlacklistApp {
    /**
     * Creates a new BlacklistApp instance.
     * @param {Partial<BlacklistApp>} [$$source = {}] - The source object to create the BlacklistApp.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("processName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["processName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlacklistApp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BlacklistApp}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlacklistApp(/** @type {Partial<BlacklistApp>} */($$parsedSource));
    }
}

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("blacklist" in $$source)) {
            /**
             * @member
             * @type {BlacklistApp[]}
             */
            this["blacklist"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blacklist" in $$parsedSource) {
            $$parsedSource["blacklist"] = $$createField0_0($$parsedSource["blacklist"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Mode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ModeQuiet: "quiet",
    ModeKill: "kill",
};

export class SessionRecord {
    /**
     * Creates a new SessionRecord instance.
     * @param {Partial<SessionRecord>} [$$source = {}] - The source object to create the SessionRecord.
     */
    constructor($$source = {}) {
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (!("endedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["endedAt"] = null;
        }
        if (!("durationMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMin"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {Mode}
             */
            this["mode"] = Mode.$zero;
        }
        if (!("apps" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["apps"] = [];
        }
        if (!("autoEnded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoEnded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionRecord}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apps" in $$parsedSource) {
            $$parsedSource["apps"] = $$createField4_0($$parsedSource["apps"]);
        }
        return new SessionRecord(/** @type {Partial<SessionRecord>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = BlacklistApp.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
