// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is bound to the frontend. Every exported method here becomes a
 * callable JS/TS function via the generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "./internal/session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * EndSession is called once the frontend's own anti-laziness confirmation
 * (countdown + explicit confirm) has completed.
 * @returns {$CancellablePromise<store$0.SessionRecord>}
 */
export function EndSession() {
    return $Call.ByID(486088225).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<store$0.Config>}
 */
export function GetConfig() {
    return $Call.ByID(3902498144).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<store$0.SessionRecord[]>}
 */
export function GetHistory(limit) {
    return $Call.ByID(258093614, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<session$0.Info>}
 */
export function GetState() {
    return $Call.ByID(800887515).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListRunningApps returns the names of currently running foreground apps, so
 * the frontend can offer a pick-list instead of requiring the user to look up
 * exact process names in Activity Monitor. The names returned here are the
 * same ones macOS uses internally, so they also work directly as the
 * `pkill -x` target for kill mode.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListRunningApps() {
    return $Call.ByID(1521617085).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SaveBlacklist replaces the whole blacklist with the given list.
 * @param {store$0.BlacklistApp[]} apps
 * @returns {$CancellablePromise<store$0.Config>}
 */
export function SaveBlacklist(apps) {
    return $Call.ByID(3447760090, apps).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * StartSession begins blocking the current blacklist using the given mode
 * ("quiet" or "kill"). durationMin <= 0 means the session only ends manually.
 * @param {string} mode
 * @param {number} durationMin
 * @returns {$CancellablePromise<session$0.Info>}
 */
export function StartSession(mode, durationMin) {
    return $Call.ByID(13616470, mode, durationMin).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = store$0.SessionRecord.createFrom;
const $$createType1 = store$0.Config.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = session$0.Info.createFrom;
const $$createType4 = $Create.Array($Create.Any);
